/**
 * GroqNLMAnalysis.jsx
 *
 * Displays the Groq llama-3.3-70b forensic report generated by the backend.
 * Falls back to calling Groq via Puter.js (client-side) if the backend
 * NLM report is missing, or shows a local deterministic report as last resort.
 */
import React, { useState, useEffect } from 'react';
import BrutalCard from '../ui/BrutalCard';
import { Loader, Brain, CheckCircle, AlertTriangle } from 'lucide-react';

export default function GrokNLMAnalysis({ ltcaData, masScore }) {
    const [report, setReport] = useState('');
    const [source, setSource] = useState(''); // 'groq-backend' | 'puter' | 'local'
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (!ltcaData) { setLoading(false); return; }

        // ── Primary: backend Groq report ───────────────────────────────────────
        if (ltcaData.nlm_report && ltcaData.nlm_report.length > 50) {
            setReport(ltcaData.nlm_report);
            setSource('groq-backend');
            setLoading(false);
            return;
        }

        // ── Secondary: Puter.js client-side Grok ──────────────────────────────
        generateWithPuter();
    }, [ltcaData]);

    async function generateWithPuter() {
        try {
            const puter = window.puter;
            if (!puter) throw new Error('Puter not available');

            // Silently check if the user is authenticated BEFORE making any AI call.
            // This prevents the api.puter.com/whoami 401 from appearing in the console.
            let isAuthenticated = false;
            try {
                const user = await puter.auth.getUser();
                isAuthenticated = !!(user && user.uuid);
            } catch {
                isAuthenticated = false;
            }

            if (!isAuthenticated) {
                // Skip straight to local report — do not call puter.ai which triggers whoami
                throw new Error('Puter: not authenticated');
            }

            const isFake = ltcaData?.is_fake ?? false;
            const curvature = (ltcaData?.curvature_score ?? 0).toFixed(3);
            const velocityVar = (ltcaData?.velocity_variance ?? 0).toFixed(3);
            const verdict = masScore < 40 ? 'Authentic' : masScore >= 60 ? 'AI-Generated Deepfake' : 'Suspicious';

            const prompt = `You are a senior digital forensics analyst. Write a 3-paragraph plain text forensic report (no headers, no markdown) based on these scan metrics:

MAS Score: ${masScore?.toFixed(1)}/100 (higher=more AI)
Physics Flagged: ${isFake} | Curvature: ${curvature} | Velocity Variance: ${velocityVar}
Physics Diagnosis: ${ltcaData?.reason ?? 'N/A'}
Verdict: ${verdict}

Para 1: Executive verdict. Para 2: Explain the metrics. Para 3: Recommendation.`;

            const response = await puter.ai.chat(prompt, { model: 'x-ai/grok-4-1-fast' });
            const text = response?.message?.content ?? String(response);
            setReport(text);
            setSource('puter');
        } catch {
            // Last resort: local deterministic report
            setReport(buildLocalReport(ltcaData, masScore));
            setSource('local');
        } finally {
            setLoading(false);
        }
    }


    const sourceLabel = {
        'groq-backend': { text: 'Groq · Llama 3.3 70B', color: 'text-ds-cyan' },
        'puter': { text: 'Grok 4.1 via Puter', color: 'text-ds-green' },
        'local': { text: 'Local Engine', color: 'text-ds-silver/40' },
    }[source] ?? { text: '', color: '' };

    // Derive verdict styling
    const isFlagged = masScore >= 60;
    const isClean = masScore < 40;

    return (
        <BrutalCard className="overflow-hidden border-ds-silver/10">
            {/* Header bar */}
            <div className={`px-6 py-4 flex items-center justify-between gap-4 border-b border-ds-silver/10
        ${isFlagged ? 'bg-ds-red/5 border-l-4 border-l-ds-red'
                    : isClean ? 'bg-ds-green/5 border-l-4 border-l-ds-green'
                        : 'bg-ds-yellow/5 border-l-4 border-l-ds-yellow'}`}>
                <div className="flex items-center gap-3">
                    <Brain className={`w-5 h-5 ${isFlagged ? 'text-ds-red' : isClean ? 'text-ds-green' : 'text-ds-yellow'}`} />
                    <div>
                        <h3 className="font-grotesk font-black text-ds-silver text-base uppercase tracking-widest leading-none">
                            <span className="text-ds-cyan">[NLM]</span> Deep Expert Analysis
                        </h3>
                        {source && (
                            <p className={`text-[10px] font-mono mt-0.5 ${sourceLabel.color}`}>
                                ⚡ {sourceLabel.text}
                            </p>
                        )}
                    </div>
                </div>

                {/* Verdict chip */}
                {!loading && (
                    <div className={`flex items-center gap-1.5 px-3 py-1 text-xs font-mono font-bold border
            ${isFlagged ? 'text-ds-red border-ds-red bg-ds-red/10'
                            : isClean ? 'text-ds-green border-ds-green bg-ds-green/10'
                                : 'text-ds-yellow border-ds-yellow bg-ds-yellow/10'}`}>
                        {isFlagged ? <AlertTriangle className="w-3.5 h-3.5" /> : <CheckCircle className="w-3.5 h-3.5" />}
                        {isFlagged ? 'DEEPFAKE DETECTED' : isClean ? 'AUTHENTIC' : 'UNDER REVIEW'}
                    </div>
                )}
            </div>

            {/* Body */}
            <div className="px-6 py-5">
                {loading ? (
                    <div className="flex items-center gap-3 text-ds-silver/50 font-mono text-sm py-4">
                        <Loader className="w-4 h-4 animate-spin text-ds-cyan flex-shrink-0" />
                        <span>Generating forensic analysis with Groq AI (Llama 3.3 70B)...</span>
                    </div>
                ) : (
                    <div className="space-y-4">
                        {report
                            .split('\n\n')
                            .filter(p => p.trim())
                            .map((paragraph, i) => (
                                <p
                                    key={i}
                                    className={`font-mono text-sm leading-relaxed ${i === 0
                                        ? 'text-ds-silver font-semibold'      // first para = executive summary — brighter
                                        : i === report.split('\n\n').filter(p => p.trim()).length - 1
                                            ? 'text-ds-cyan/90'                 // last para = recommendation — accent
                                            : 'text-ds-silver/70'               // middle = detail — dimmer
                                        }`}
                                >
                                    {paragraph.trim()}
                                </p>
                            ))}
                    </div>
                )}
            </div>
        </BrutalCard>
    );
}

function buildLocalReport(ltcaData, masScore) {
    const isFake = ltcaData?.is_fake ?? false;
    const curvature = (ltcaData?.curvature_score ?? 0).toFixed(3);
    const velocityVar = (ltcaData?.velocity_variance ?? 0).toFixed(3);
    const verdict = masScore < 40 ? 'AUTHENTIC' : masScore >= 60 ? 'AI-GENERATED DEEPFAKE' : 'UNCERTAIN';

    const p1 = `Deepscan's forensic pipeline assigned a Media Authenticity Score of ${masScore?.toFixed(1)}/100, classifying this media as '${verdict}'.`;
    const p2 = isFake
        ? `The LTCA Physics Engine raised a flag — Curvature Score of ${curvature} (threshold <0.25) indicates latent trajectory collapse, a hallmark of AI diffusion generation. Velocity Variance of ${velocityVar} confirms physically impossible inter-frame motion.`
        : `The LTCA Physics Engine found no violations: Curvature Score ${curvature} and Velocity Variance ${velocityVar} are both within natural ranges for real camera capture.`;
    const p3 = masScore < 30
        ? 'RECOMMENDATION: CLEAR — No indicators of AI generation or manipulation detected.'
        : masScore < 55
            ? 'RECOMMENDATION: FURTHER REVIEW RECOMMENDED — Mixed signals detected across detection engines.'
            : 'RECOMMENDATION: FLAG AS SYNTHETIC MEDIA — Multiple forensic engines converged on AI-generation classification.';

    return `${p1}\n\n${p2}\n\n${p3}`;
}
