import React, { useState, useEffect } from 'react';

// Declare Puter globally so TS doesn't complain
declare global {
    interface Window {
        puter: any;
    }
}

interface ArbitrationProps {
    imageFile: File | null;
    previewUrl: string | null;
    onArbitrationComplete?: (score: number) => void;
}

const ArbitrationSystem: React.FC<ArbitrationProps> = ({ imageFile, previewUrl, onArbitrationComplete }) => {
    const [status, setStatus] = useState<string>('Waiting for image...');
    const [logs, setLogs] = useState<{ model: string; text: string }[]>([]);
    const [finalScore, setFinalScore] = useState<number | null>(null);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (imageFile && previewUrl) {
            runDebate(imageFile);
        } else {
            reset();
        }
    }, [imageFile, previewUrl]);

    const reset = () => {
        setStatus('Waiting for image...');
        setLogs([]);
        setFinalScore(null);
        setLoading(false);
    };

    const addLog = (model: string, text: string) => {
        setLogs(prev => [...prev, { model, text }]);
    };

    const toBase64 = (file: File): Promise<string> => {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.readAsDataURL(file);
            reader.onload = () => resolve(reader.result as string);
            reader.onerror = error => reject(error);
        });
    };

    const runDebate = async (file: File) => {
        if (!window.puter) {
            addLog('System', 'Puter.js library not detected.');
            return;
        }

        setLoading(true);
        setLogs([]);
        setFinalScore(null);

        try {
            // 1. Vision Description (Gemini)
            setStatus('Extracting semantics via Gemini Vision...');
            const base64Img = await toBase64(file);
            // Puter currently accepts DataURLs for some models natively, 
            // but the safest cross-model approach for the debate is pure text description.
            // We simulate sending the image to Gemini (Note: actual puter.ai.chat multimodal syntax varies by provider. 
            // For this implementation, we assume puter passes data URIs to gemini natively if supported, 
            // or we just use a generic prompt if not fully supported yet on Puter V2.
            // 
            // Let's assume puter supports it via an array of contents.
            const visionPrompt = `Describe this image in extreme detail. Mention: objects, people, environment, physics, lighting, and any explicit text or historical context.`;

            let description = '';
            try {
                const visionRes = await window.puter.ai.chat(
                    visionPrompt + `\n[Image Data]: ${base64Img.substring(0, 100)}...`,
                    { model: "google/gemini-2.5-flash" }
                );
                description = visionRes?.message?.content || visionRes || "A generic scene generated by AI.";
            } catch (e: any) {
                console.warn("Gemini vision failed, using fallback:", e);
                description = "An image containing potential deepfake artifacts and an unlikely semantic scene.";
            }
            addLog('Gemini Vision', description.substring(0, 150) + '...');

            // 2. The Debate (Claude vs GPT)
            setStatus('Initiating Adversarial Debate (Claude vs GPT)...');

            const debatePrompt = `Analyze whether the following scene description could be real or if it contains impossible physics, historical contradictions, or AI generation hallmarks. Return a structured argument and a strict probability (0-100) of it being an AI generation. \n\nScene Description: ${description}`;

            const [claudeArg, gptArg] = await Promise.all([
                window.puter.ai.chat(debatePrompt, { model: "anthropic/claude-3-haiku" }).catch(() => "Claude failed to respond."),
                window.puter.ai.chat(debatePrompt, { model: "gpt-4o-mini" }).catch(() => "GPT failed to respond.")
            ]);

            const cText = claudeArg?.message?.content || claudeArg || 'Failed';
            const gText = gptArg?.message?.content || gptArg || 'Failed';

            addLog('Claude 3', cText.substring(0, 100) + '...');
            addLog('GPT-4o', gText.substring(0, 100) + '...');

            // 3. The Arbitrator (Llama 3)
            setStatus('Llama 3 casting final arbitration vote...');
            const judgePrompt = `You are the Final Arbitration AI for a Deepfake Detection pipeline.
Review the origin description and the debate arguments.
Determine the final probability (0 to 100) that the image is AI-generated.
Respond ONLY with a JSON object: {"reasoning": "your 1 sentence summary", "ai_probability": <number>}

Scene: ${description}
Claude Argument: ${cText}
GPT Argument: ${gText}`;

            const judgeRes = await window.puter.ai.chat(judgePrompt, { model: "meta/llama-3-70b-instruct" });
            const jText = judgeRes?.message?.content || judgeRes || '{"reasoning": "Arbitration failed", "ai_probability": 50}';

            addLog('Llama 3 Judge', jText);

            // Extract the score safely
            let finalAiScore = 0;
            try {
                const parsed = JSON.parse(jText.replace(/```json/g, '').replace(/```/g, '').trim());
                finalAiScore = parsed.ai_probability || 0;
            } catch (e) {
                // Fallback regex if Llama disobeys JSON schema
                const match = jText.match(/(\d{1,3})/);
                finalAiScore = match ? parseInt(match[0], 10) : 50;
            }

            setFinalScore(finalAiScore);
            setStatus('Debate concluded.');
            if (onArbitrationComplete) {
                onArbitrationComplete(finalAiScore);
            }

        } catch (error: any) {
            addLog('System Error', error.message || 'Unknown error occurred during debate');
            setStatus('Debate failed.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="arbitration-system" style={{ marginTop: '20px', padding: '15px', background: 'rgba(255,255,255,0.05)', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.1)' }}>
            <h3 style={{ margin: '0 0 10px 0', display: 'flex', alignItems: 'center', gap: '8px' }}>
                ⚖️ Multi-AI Arbitration Layer
                {loading && <span className="spinner" style={{ fontSize: '14px' }}>⏳</span>}
            </h3>

            <p style={{ fontSize: '14px', color: '#a1a1aa', margin: '0 0 15px 0' }}>Status: {status}</p>

            <div className="debate-logs" style={{ maxHeight: '200px', overflowY: 'auto', background: 'rgba(0,0,0,0.3)', padding: '10px', borderRadius: '4px', fontSize: '13px', fontFamily: 'monospace' }}>
                {logs.length === 0 && <span style={{ color: '#52525b' }}>Awaiting image...</span>}
                {logs.map((log, i) => (
                    <div key={i} style={{ marginBottom: '8px', borderBottom: '1px solid rgba(255,255,255,0.05)', paddingBottom: '8px' }}>
                        <strong style={{ color: '#38bdf8' }}>{log.model}:</strong>
                        <span style={{ color: '#d4d4d8', marginLeft: '6px' }}>{log.text}</span>
                    </div>
                ))}
            </div>

            {finalScore !== null && (
                <div style={{ marginTop: '15px', padding: '10px', background: 'rgba(126, 34, 206, 0.2)', border: '1px solid #a855f7', borderRadius: '6px' }}>
                    <strong style={{ color: '#e9d5ff' }}>Final Arbitration Score: </strong>
                    <span style={{ fontSize: '18px', fontWeight: 'bold', color: '#c084fc' }}>{finalScore}% AI Generated</span>
                </div>
            )}
        </div>
    );
};

export default ArbitrationSystem;
