import os
import json
from loguru import logger
from backend.utils.hf_api import query_huggingface

class VideoNLMReport:
    """
    Acts as an expert Deepfake Forensic Analyst language model.
    It takes the raw mathematical physics generated by the LTCA and Noise engines
    and translates it into a deep, human-readable paragraph explaining *how* it's fake.
    """
    def __init__(self):
        # We use a reliable instruction-tuned model via HF API
        self.model_url = "https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct"

    async def generate_report(self, mas_score: float, spatial_score: float, temporal_penalty: float, 
                              noise_score: float, ltca_data: dict) -> str:
        """
        Generates a deep forensic analysis based on the numerical data.
        """
        logger.info("Triggering Deep NLM for video forensic explanation...")

        ltca_suspect = ltca_data.get('is_fake', False)
        curvature = ltca_data.get('curvature_score', 0)
        
        # Determine the overall verdict context
        verdict = "Authentic Video" if mas_score < 40 else "AI-Generated Deepfake" if mas_score >= 60 else "Suspicious/Manipulated"
        
        # Construct the context prompt containing the pure mathematical facts
        context = f"""
        You are a highly advanced digital forensics AI expert. I have just scanned a video file using mathematical engines.
        Your job is to read the data below and output a 2-3 paragraph "Forensic Report" explaining to the user exactly WHY the video was flagged as {verdict}, or why it is authentic.
        
        Here is the Deepscan Mathematics Data:
        - Final Authenticity Score (Higher = Faker): {mas_score:.1f}/100.
        - Visual Transformer Anomaly Score: {spatial_score:.1f}/100. (Detects strange surface pixels).
        - Optical Flow Flicker Penalty: {temporal_penalty:.1f}/100. (Detects unnatural pixel morphing between frames).
        - Sensor Noise Signature Score: {noise_score:.1f}/100. (High means synthetic diffusion grid artifacts, low means natural camera PRNU).
        - R(2+1)D Latent Trajectory (Physics Engine): Flagged as Physics Violation? {ltca_suspect}.
        - Latent Smoothness Curve: {curvature:.2f}. (Scores below 0.65 mean the motion in the video 'zig-zagged' impossibly, a hallmark of AI lacking real-world momentum).
        
        Instructions:
        1. Write in the tone of a professional, serious cybersecurity analyst.
        2. Specifically mention the mathematical metrics above if they are highly suspicious or highly authentic.
        3. Explain *how* the AI generator failed (e.g. "The latent physics engine detected a severe vector collapse, indicating the diffusion model failed to maintain temporal inertia during the character's movement.")
        4. Do not use markdown headers, just output the paragraphs.
        """
        
        # Format payload for Llama-3 Instruct
        prompt = f"<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n{context}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
        payload = {
            "inputs": prompt,
            "parameters": {
                "max_new_tokens": 300,
                "temperature": 0.3, # Keep it analytical and objective
                "return_full_text": False
            }
        }
        
        try:
            hf_token = os.getenv("HF_API_TOKEN")
            if not hf_token:
                return "The Deep NLM is currently offline because the required Hugging Face API token is not configured in the environment. Raw data suggests the video is: " + verdict
                
            response = await query_huggingface(self.model_url, payload=payload)
            
            if response and isinstance(response, list) and "generated_text" in response[0]:
                report = response[0]["generated_text"].strip()
                logger.success("Deep NLM analysis successful.")
                return report
            else:
                logger.error(f"NLM formatting issue: {response}")
                return self._fallback_report(mas_score, verdict, ltca_suspect)
                
        except Exception as e:
            logger.error(f"Failed to generate Deep NLM Report: {e}")
            return self._fallback_report(mas_score, verdict, ltca_suspect)
            
    def _fallback_report(self, score, verdict, physics_fail):
        report = f"The Deepscan pipeline computed a Media Authenticity Score of {score:.1f}/100, resulting in a classification of '{verdict}'."
        if physics_fail:
            report += " The Latent Trajectory model completely flagged the physical momentum of this video, identifying severe vector anomalies synonymous with AI diffusion generation."
        return report
